#!/bin/sh
# This is a generated file; do not edit or check into version control.
export "FLUTTER_ROOT=/Users/watanaberyuunosuke/Development/dependecies/flutter_macos_1.20.1-stable"
export "FLUTTER_APPLICATION_PATH=/Users/watanaberyuunosuke/Development/projects/independent_view_sample"
export "FLUTTER_TARGET=/Users/watanaberyuunosuke/Development/projects/independent_view_sample/lib/main.dart"
export "FLUTTER_BUILD_DIR=build"
export "SYMROOT=${SOURCE_ROOT}/../build/ios"
export "OTHER_LDFLAGS=$(inherited) -framework Flutter"
export "FLUTTER_FRAMEWORK_DIR=/Users/watanaberyuunosuke/Development/dependecies/flutter_macos_1.20.1-stable/bin/cache/artifacts/engine/ios"
export "FLUTTER_BUILD_NAME=1.0.0"
export "FLUTTER_BUILD_NUMBER=1"
export "DART_DEFINES=flutter.inspector.structuredErrors%3Dtrue"
export "DART_OBFUSCATION=false"
export "TRACK_WIDGET_CREATION=true"
export "TREE_SHAKE_ICONS=false"
export "PACKAGE_CONFIG=.packages"
